# Generated by Django 2.2.11 on 2020-03-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=1)),
                ('rollno', models.IntegerField()),
                ('mobileno', models.IntegerField(primary_key=True, serialize=False)),
                ('isTeamLeader', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=10)),
                ('isGroup', models.BooleanField(default=False)),
                ('cgpa', models.FloatField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('groupid', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
