# Generated by Django 2.2.11 on 2020-03-23 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobileNo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollNo', models.IntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobileNo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='topics')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('isTaken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=1)),
                ('rollNo', models.IntegerField()),
                ('mobileNo', models.IntegerField(primary_key=True, serialize=False)),
                ('cgpa', models.FloatField(default=0.0)),
                ('bio', models.TextField()),
                ('isTeamLeader', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=10)),
                ('isGrouped', models.BooleanField(default=False)),
                ('isAssigned', models.BooleanField(default=False)),
                ('groupId', models.IntegerField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('modifiedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ProjectGroup')),
                ('lastModifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Topic'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='student.UserProfile'),
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.FileField(upload_to='presentations')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('modifiedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ProjectGroup')),
                ('lastModifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile')),
            ],
        ),
    ]
