# Generated by Django 2.2.11 on 2020-03-20 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobileNo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('groupId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('rno', models.IntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobileNo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=80)),
                ('document', models.FileField(upload_to='uploads/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=1)),
                ('rollno', models.IntegerField()),
                ('mobileno', models.IntegerField(primary_key=True, serialize=False)),
                ('isTeamLeader', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=10)),
                ('isGroup', models.BooleanField(default=False)),
                ('groupId', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ProjectGroup')),
            ],
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Topic'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='student.UserProfile'),
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.FileField(upload_to='presentations/')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ProjectGroup')),
            ],
        ),
    ]
