# Generated by Django 2.2.11 on 2020-03-16 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('rno', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=80)),
                ('document', models.FileField(upload_to='uploads/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.FileField(upload_to='presentations/')),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Topic'),
        ),
        migrations.AddField(
            model_name='group',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='user4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='student.UserProfile'),
        ),
    ]
