# Generated by Django 2.2.11 on 2020-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200320_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
