# Generated by Django 2.2.11 on 2020-03-16 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200316_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ProjectGroup',
        ),
        migrations.AddField(
            model_name='ppt',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
