# Generated by Django 2.2.11 on 2020-03-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200316_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='mobileno',
            new_name='mobileNo',
        ),
        migrations.RenameField(
            model_name='ppt',
            old_name='groupid',
            new_name='groupName',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='groupid',
            new_name='groupName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='mobileno',
            new_name='mobileNo',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='rno',
            new_name='rollNo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='groupid',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='isGroup',
            new_name='isGrouped',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='rollno',
            new_name='rollNo',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='groupid',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='groupName',
            field=models.CharField(default='Unamed group', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
