# Generated by Django 2.2.11 on 2020-03-28 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200328_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='createdOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
