# Generated by Django 2.2.11 on 2020-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200328_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
