# Generated by Django 2.2.11 on 2020-03-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200316_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt',
            old_name='groupName',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='groupName',
            new_name='groupId',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groupName',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='groupId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groupId',
            field=models.IntegerField(default=0),
        ),
    ]
