# Generated by Django 2.2.11 on 2020-03-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200316_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='rollNo',
            new_name='rno',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='rollNo',
            new_name='rollno',
        ),
    ]
