# Generated by Django 2.2.11 on 2020-03-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200316_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isGrouped',
            new_name='isGroup',
        ),
    ]
