# Generated by Django 2.2.11 on 2020-03-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200328_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='student.UserProfile'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='student.UserProfile'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='student.UserProfile'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='user4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='student.UserProfile'),
        ),
    ]
