# Generated by Django 2.2.11 on 2020-03-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200329_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserProfile'),
        ),
    ]
